### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by excxapp** [Blocklevel/vue-howler#1]
XMLHttpRequest cannot load http://ws.stream.qqmusic.qq.com/107661650.m4a?fromtag=46. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.baidu.com' is therefore not allowed access.

**Comment by mickdekkers** [comment]
Hey, sorry for the late reply.

This is [a Same Origin Policy restriction](http://stackoverflow.com/a/20035319), and I'm afraid it's not easy to bypass unless the stream server has [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) enabled.

You could use a CORS proxy such as [this one](https://crossorigin.me/) or [this one](https://cors-anywhere.herokuapp.com/), but there are no uptime guarantees unless you [set up your own instance](https://github.com/gr2m/CORS-Proxy) that you control.
