### ISSUE TITLE
Add prev() and next() features

### ISSUE THREAD

**Issue by cashmash** [Blocklevel/vue-howler#17]
Just to keep it in the notes:

add

- [x] prev()
- [x] next()

**Comment by mickdekkers** [comment]
Hey @cashmash, thanks for your suggestion 🙂 

What do you think these functions should do?

**Comment by cashmash** [comment]
Hi @mickdekkers , sorry for the late reply.

It would be two functions to play the next and previous audio.

**Comment by mickdekkers** [comment]
@cashmash no worries :)

I need to document this better, but you can do this right now by changing the contents of the sources array.
See https://github.com/Blocklevel/vue-howler/issues/8#issuecomment-326244972

If you want to create an audio player with a playlist, you could make a playlist component that passes the sources array to an audio player component. On the playlist component, you could implement `next()` and `prev()` like this:

```js
// you could e.g. put this in data or pass it through props
const playlist = [
  ['audio-1.mp3', 'audio-1.wav'],
  ['audio-2.mp3', 'audio-2.wav'],
  ['audio-3.mp3', 'audio-3.wav']
]

export default {
  data () {
    return {
      playlistIndex: 0
    }
  },

  methods: {
    prev () {
      this.playlistIndex = Math.max(0, this.playlistIndex - 1)
    },
    next () {
      this.playlistIndex = Math.min(playlist.length - 1, this.playlistIndex + 1)
    }
  },

  computed: {
    currentSources () {
      return playlist[this.playlistIndex]
    }
  }
}
```

Then you can pass `currentSources` to the audio player component:
```vue
<template>
  <audio-player :sources="currentSources"/>
  <button @click="prev">prev</button>
  <button @click="next">next</button>
</template>
```

**Comment by cashmash** [comment]
Thank you, looks good.

**Comment by brmly** [comment]
`this.playlistIndex = Math.min(playlist.length, this.playlistIndex + 1)`
=>
`this.playlistIndex = Math.min(playlist.length `**- 1**`, this.playlistIndex + 1)`

**Comment by mickdekkers** [comment]
@brmly right, thanks for the fix! :smile: I updated my comment.

**Comment by paperscissors** [comment]
Seems like this only works if autoplay is set to true. Anyone else can confirm and also know of a workaround?
