### ISSUE TITLE
How make a playlist?

### ISSUE THREAD

**Issue by demokrrat** [Blocklevel/vue-howler#24]
Hi, how can I make a playlist with skipTo()?

**Comment by mickdekkers** [comment]
Hi, you can implement a playlist [like this](https://github.com/mickdekkers/vue-howler/issues/17#issuecomment-338383282). You basically keep track of the playlist index in a parent component, and update the `sources` array when you want to change the audio (this is what the `currentSources` computed property is for). You can then add a `skipTo(index)` method to the parent like this:

```js
skipTo (index) {
  this.playlistIndex = index
}
```

You may want to clamp the index argument between `0` and `playlist.length - 1` to ensure it doesn't go out of bounds.

**Comment by demokrrat** [comment]
Thanks

**Comment by mickdekkers** [comment]
👍
