### ISSUE TITLE
Play sound on component's notification

### ISSUE THREAD

**Issue by Extarys** [Blocklevel/vue-howler#29]
I'm trying to modify iview to play a different sound depending of the notification type.
`VueHowler.sources(['~/assets/system_success.wav'])` doesn't work, I get:

`An array of source files must be passed with any new Howl.
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'length' of undefined"
`

How can I play a single sound automatically? The documentation is short on that end :)

thanks!

**Comment by mickdekkers** [comment]
Hi! If you just want to play a single sound, you're probably better off using Howler.js directly. They have [an example](https://github.com/goldfire/howler.js#most-basic-play-an-mp3) that may be of help. `vue-howler` was developed to make it easier to develop fully-featured audio player UIs, but it's probably unnecessary if you just want to get an audio file to play 🙂

**Comment by Extarys** [comment]
I see! Thank you very much!
