### ISSUE TITLE
multiple players controlling single context

### ISSUE THREAD

**Issue by walleXD** [Blocklevel/vue-howler#3]
Hi,

Thanks for adding html5 to the prop. I am trying to create multiple players with the same howler context. What would be the best way to do so using vuex? Any thoughts?

Thanks!

**Comment by mickdekkers** [comment]
Could you clarify what you mean by howler context? Are you referring to this? https://github.com/goldfire/howler.js/blob/master/README.md#ctx-boolean-web-audio-only

**Comment by walleXD** [comment]
I was thinking of the best way to control a single instance of the vue-howler component from other parent component or global state (vuex). Would it be possible to expose the play option as a prop? So, if play is passed as a prop or something like that. What would be the best way to do so?

**Comment by mickdekkers** [comment]
Hey, sorry for the delay.

If I'm understanding it right, you want to be able to control a player component externally.

You probably want to use a [global event bus](https://alligator.io/vuejs/global-event-bus/):

`bus.js`
```js
export default new Vue()
```

`audio-player.vue`
```vue
<script>
  import VueHowler from 'vue-howler'
  import bus from './bus'

  export default {
    mixins: [VueHowler],

    mounted () {
      // Register event listeners
      bus.$on('audio-play', this.play)

      bus.$on('audio-stop', this.stop)
    },

    beforeDestroy () {
      // Clean up event listeners
      bus.$off('audio-play', this.play)

      bus.$off('audio-stop', this.stop)
    }
  }
</script>

<template>
  <div>
    <span>Total duration: {{ duration }} seconds</span>
    <span>Progress: {{ (progress * 100) }}%</span>
    <button @click="togglePlayback">{{ playing ? 'Pause' : 'Play' }}</button>
    <button @click="stop">Stop</button>
  </div>
</template>
```

`some-other-component.vue`
```vue
<script>
  import bus from './bus'

  export default {
    computed: {
      bus () {
        return bus
      }
    }
  }
</script>

<template>
  <div>
    <button @click="bus.$emit('audio-start')">Start all players</button>
    <button @click="bus.$emit('audio-stop')">Stop all players</button>
  </div>
</template>
```

---

It's possible, but not recommended, to access the methods of components by [using a ref](https://vuejs.org/v2/guide/components.html#Child-Component-Refs):

`audio-player-parent.vue`
```vue
<template>
  <audio-player ref="player" :sources="audioSources">
</template>

<script>
  import AudioPlayer from './audio-player.vue'

  export default {
    components: {
       AudioPlayer
    },

    methods: {
      startAudioPlayer () {
        if (this.$refs.player) {
          this.$refs.player.play()
        }
      }
    }
  }
</script>
```

---

It's also possible, though also not recommended, to watch the vuex store directly in the player component:

`audio-player.vue`
```vue
<script>
  import VueHowler from 'vue-howler'
  import { mapGetters } from 'vuex'

  export default {
    mixins: [VueHowler],

    computed: {
      ...mapGetters('playersShouldBePlaying')
    },

    mounted () {
      if (this.playersShouldBePlaying) {
        this.play()
      } else {
        this.stop()
      }
    },

    watch: {
      playersShouldBePlaying (val) {
        if (val) {
          this.play()
        } else {
          this.stop()
        }
      }
    }
  }
</script>

<template>
  <div>
    <span>Total duration: {{ duration }} seconds</span>
    <span>Progress: {{ (progress * 100) }}%</span>
    <button @click="togglePlayback">{{ playing ? 'Pause' : 'Play' }}</button>
    <button @click="stop">Stop</button>
  </div>
</template>
```

**Comment by walleXD** [comment]
Going to give this a try 👍

**Comment by mickdekkers** [comment]
@walleXD I'm closing this issue for now, but feel free to comment again if it isn't resolved yet and I'll reopen it.
