### ISSUE TITLE
The total duration of the audio changes constantly.

### ISSUE THREAD

**Issue by Leo1653** [Blocklevel/vue-howler#30]
Dear author！
     I'd like to ask you a question，every time I change currentTIme，duration is also changing！this is a problem I have with my own development, not with your plugin. Your plugin is perfect, my friend will not encounter this problem when using your plugin! At the beginning, the obtained duration is the final duration! How did you handle it?

**Comment by mickdekkers** [comment]
Hi! That's strange, I'm not sure what would cause that 🤔
This plugin obtains the duration directly from Howler.js: https://github.com/mickdekkers/vue-howler/blob/9fb113eca431d7e131655ad4a36256bc6cb5f36f/src/index.js#L122
It uses the Howl object's `duration()` method: https://github.com/goldfire/howler.js/#durationid
Perhaps you could try asking on [their issue tracker](https://github.com/goldfire/howler.js/issues)? 🙂

**Comment by Leo1653** [comment]
> 嗨！这很奇怪，我不确定是什么原因引起的🤔
> 此插件直接从Howler.js获取持续时间：
> 
> [VUE-吼/ SRC / index.js](https://github.com/mickdekkers/vue-howler/blob/9fb113eca431d7e131655ad4a36256bc6cb5f36f/src/index.js#L122)
> 
> [9fb113e中的](/mickdekkers/vue-howler/commit/9fb113eca431d7e131655ad4a36256bc6cb5f36f) 第122 [行](/mickdekkers/vue-howler/commit/9fb113eca431d7e131655ad4a36256bc6cb5f36f)
> 
>  这个。持续时间 =  这个。$ data。_howl。持续时间（）
> 
> 它使用Howl对象的`duration()`方法：[https](https://github.com/goldfire/howler.js/#durationid)：[//github.com/goldfire/howler.js/#durationid](https://github.com/goldfire/howler.js/#durationid)
> 也许您可以尝试询问[他们的问题跟踪器](https://github.com/goldfire/howler.js/issues)？🙂

**Comment by Leo1653** [comment]
ok！Thank you for your reply!
