### ISSUE TITLE
Source not working

### ISSUE THREAD

**Issue by walleXD** [Blocklevel/vue-howler#4]
Hi,

I got this source to work before but recently it stopped working. Any ideas @mickdekkers? I was using it with :html5="prop" as it's a radio stream. Links to audio files work but I can't get the stream to work for some reason

Thanks for all the help

**_Edit_**: It seems for some weird reason streams are not working as direct MP3 files work. I even tried some of the radio streams from Howler's examples but hasn't been able to get it to work

**_Edit2_**: It does work but once the button is clicked, it takes a very long time to load .... couple of mins. Any thoughts on why that happens @mickdekkers?

**_Edit3_**: Found the culprit:
```
v-btn(
          floating,
          info,
          @click.native="togglePlayback"
        )
```
It seems the buttons in vuetify needs to emit native dom events for some reason. Any how, it's a vuetify issue. 

**_Edit4_**: The main issue still remains. It seems that the stream of my interest still doesn't play. So ```          'http://ice1.somafm.com/indiepop-128-mp3'
``` from Howler examples play instantly while my stream doesn't seem to play ```'http://streams.museter.com:8629/stream'```, any ideas? Also, it seems that my stream does work with the basic radio example in howler docs.

**_Edit5_**: it seems the issue arises when there are multiple stream urls in the array of sources. I get this error:
```
GET http://streams.museter.com:8629/stream,http://ice1.somafm.com/indiepop-128-mp3 net::ERR_EMPTY_RESPONSE
```
With the following sources:
```
source: [
          'http://streams.museter.com:8629/stream',
          'http://ice1.somafm.com/indiepop-128-mp3'
        ]
```
Is this an expected behaviour with live streams? Or am I doing something wrong? 

 Thanks for all the help!

**Comment by mickdekkers** [comment]
This is most likely an issue with Howler.js itself, because vue-howler doesn't really touch the sources array or any of the other input: it just passes it along to a Howl instance.

That said, I just released vue-howler@0.3.2 which updates the Howler.js dependency to 2.0.4.
Could you check if the issue is still present? Thanks =)
