### ISSUE TITLE
support events

### ISSUE THREAD

**Issue by faroit** [Blocklevel/vue-howler#6]
first, thanks for this great vue plugin!

is there a workaround to set `on...` events? It would be handy to get access to `onload` to implement a loading progress. I may have problems understanding what is done [here](https://github.com/Blocklevel/vue-howler/blob/master/src/index.js#L224), so this might just be a documentation issue ;-)

**Comment by mickdekkers** [comment]
Hey,

Sure, you can access `onload`.
`vue-howler` re-emits the howler.js events listed [here](https://github.com/Blocklevel/vue-howler/blob/029f128758e79812c24743a74daa8176ef7e2344/src/index.js#L99-L140) (with all the original arguments unmodified) using [Vue's $emit method](https://vuejs.org/v2/api/#vm-emit). The `hook` properties in those objects are just there to keep track of the Howl state in the mixin.

You can use [Vue's $on method](https://vuejs.org/v2/api/#vm-on) in your audio player component to create an event listener for the `load` event. For example:

```vue
<script>
  import VueHowler from 'vue-howler'

  export default {
    data () {
      return {
        loaded: false
      }
    },

    mixins: [VueHowler],

    created () {
      this.$on('load', (...args) => {
        console.log('audio loaded', ...args)
        this.loaded = true
      })
    }
  }
</script>

<template>
  <div>
    <span v-show="!loaded">Loading...</span>
    ...
  </div>
</template>
```

Unfortunately, I don't think Howler.js provides any sort of loading progress: only whether the audio has loaded or not. You can still display a loading bar/animation, but it will have to be an indeterminate one (also known as a preloader). You can find some examples of preloaders here: https://preloaders.net/

**Comment by faroit** [comment]
okay thanks. this does work perfecty

**Comment by BobNobrain** [comment]
Probably you should document this events in README?
