### ISSUE TITLE
audioSources initialisation

### ISSUE THREAD

**Issue by faroit** [Blocklevel/vue-howler#7]
How can would I implement and use the player component when I want to start with an empty `audioSources` array and update this list later so that the player loads when a new url is available?

**Comment by mickdekkers** [comment]
The Howl constructor [requires](https://github.com/goldfire/howler.js#src-array--required) a populated sources array, which makes this a bit tricky.

As a workaround, you could create a wrapper component around your audio player, which only renders the audio player when the sources are available, e.g.:
```vue
<template>
  <audio-player-inner v-if="sources.length > 0" :sources="sources"></audio-player-inner>
</template>
```
(`audio-player-inner` would use the `vue-howler` mixin)

Not pretty, but it should do the trick.

**Comment by mickdekkers** [comment]
Closing this issue for now, let me know if you have any more questions or want it reopened

**Comment by faroit** [comment]
Thanks, sorry for not confirming your proposed workaround. It does the trick! Thanks

**Comment by mickdekkers** [comment]
No worries, happy to know it worked!
